# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "243f0186b89a48231c5cc149b4ddbd6e"
name = "test-template-auth"
application_url = "https://xml-mi-conversation-standard.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1b179de1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://xml-mi-conversation-standard.trycloudflare.com/auth/callback",
  "https://xml-mi-conversation-standard.trycloudflare.com/auth/shopify/callback",
  "https://xml-mi-conversation-standard.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
